# Configuration for building documentation on readthedocs.org.

version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

python:
  version: 3.8
  install: 
    - requirements: docs/requirements.txt

submodules:
  include: all
  recursive: true
