#!/bin/bash

cp ~/.ssh/id_rsa* docker-files/
dockit --keep vpe-test && {
    rm docker-files/id_rsa*
    docker run -it --rm \
        --net=host \
        --env="DISPLAY" \
        --volume="$HOME/.Xauthority:/home/paul/.Xauthority:rw" \
        --volume="$HOME/.vim/pack/vim-vpe:/home/paul/.vim/pack/vim-vpe" \
        vpe-test
}
